package com.francescooddo.buddygrammar.core

/**
 * Maps common keywords to a single emoji so the suggestion strip can offer
 * an emoji replacement for the word being typed (or just typed).
 */
object EmojiSuggestions {
    private val keywordToEmoji: Map<String, String> = mapOf(
        "100" to "💯",
        "fire" to "🔥",
        "love" to "❤️",
        "heart" to "❤️",
        "lol" to "😂",
        "haha" to "😂",
        "laugh" to "😂",
        "ok" to "👌",
        "okay" to "👌",
        "star" to "⭐",
        "party" to "🎉",
        "sad" to "😢",
        "cool" to "😎",
        "money" to "💰",
        "pizza" to "🍕",
        "coffee" to "☕",
        "sun" to "☀️",
        "rain" to "🌧️",
        "cat" to "🐱",
        "dog" to "🐶",
        "thanks" to "🙏",
        "thank" to "🙏",
        "yes" to "✅",
        "no" to "❌",
        "idea" to "💡",
        "rocket" to "🚀",
        "happy" to "😊",
        "angry" to "😠",
        "cry" to "😭",
        "kiss" to "😘",
        "wink" to "😉",
        "beer" to "🍺",
        "wine" to "🍷",
        "music" to "🎵",
        "gift" to "🎁",
        "birthday" to "🎂",
        "snow" to "❄️",
        "moon" to "🌙",
        "tree" to "🌳",
        "flower" to "🌸",
        "book" to "📚",
        "phone" to "📱",
        "car" to "🚗",
        "plane" to "✈️",
        "home" to "🏠",
        "house" to "🏠",
        "work" to "💼",
        "clock" to "⏰",
        "eyes" to "👀",
        "strong" to "💪",
        "muscle" to "💪",
        "clap" to "👏",
        "wave" to "👋",
        "think" to "🤔",
        "sleep" to "😴",
        "goat" to "🐐",
        "win" to "🏆",
        "trophy" to "🏆",
        "soccer" to "⚽",
        "basketball" to "🏀",
        "run" to "🏃",
        "beach" to "🏖️",
        "hug" to "🤗",
        "sparkles" to "✨",
        "boom" to "💥",
        "skull" to "💀",
        "ghost" to "👻",
        "king" to "👑",
        "diamond" to "💎",
        "key" to "🔑",
        "warning" to "⚠️",
        "new" to "🆕",
        "top" to "🔝",
        "soon" to "🔜",
    )

    /** Returns the emoji for [word] (case-insensitive), or null when unmapped. */
    fun emojiFor(word: String): String? = keywordToEmoji[word.trim().lowercase()]
}
