import Foundation

public enum NextWordPredictor {
    public static let fallback = ["the", "I", "and", "to", "a"]

    static let bigrams: [String: [String]] = [
        "a": ["lot", "few", "good"],
        "about": ["the", "it", "you"],
        "after": ["the", "that", "all"],
        "all": ["the", "of", "day"],
        "am": ["going", "not", "so"],
        "and": ["then", "the", "I"],
        "any": ["questions", "time", "way"],
        "are": ["you", "we", "not"],
        "as": ["soon", "well", "long"],
        "ask": ["me", "you", "them"],
        "at": ["the", "least", "home"],
        "be": ["there", "able", "a"],
        "because": ["I", "it", "of"],
        "been": ["a", "there", "working"],
        "before": ["the", "you", "we"],
        "being": ["a", "the", "so"],
        "best": ["regards", "way", "of"],
        "big": ["deal", "day", "difference"],
        "but": ["I", "it", "the"],
        "by": ["the", "now", "tomorrow"],
        "call": ["me", "you", "later"],
        "can": ["you", "we", "I"],
        "cannot": ["wait", "believe", "make"],
        "catch": ["up", "you"],
        "come": ["over", "back", "to"],
        "could": ["you", "be", "we"],
        "did": ["you", "not", "it"],
        "do": ["you", "not", "it"],
        "does": ["not", "it", "that"],
        "doing": ["well", "great", "it"],
        "don't": ["know", "worry", "forget"],
        "down": ["the", "to", "there"],
        "each": ["other", "day", "one"],
        "every": ["day", "time", "one"],
        "feel": ["free", "like", "better"],
        "first": ["thing", "time", "of"],
        "for": ["the", "you", "me"],
        "from": ["the", "my", "you"],
        "get": ["it", "back", "together"],
        "getting": ["ready", "there", "better"],
        "give": ["me", "you", "it"],
        "go": ["to", "back", "ahead"],
        "going": ["to", "well", "home"],
        "good": ["morning", "luck", "night"],
        "got": ["it", "the", "a"],
        "great": ["job", "idea", "to"],
        "had": ["a", "to", "the"],
        "happy": ["birthday", "to", "new"],
        "has": ["been", "a", "to"],
        "have": ["a", "to", "you"],
        "having": ["a", "fun", "trouble"],
        "he": ["is", "was", "said"],
        "hear": ["from", "you", "that"],
        "her": ["and", "to", "that"],
        "here": ["is", "are", "for"],
        "his": ["own", "way", "work"],
        "hope": ["you", "that", "so"],
        "how": ["are", "much", "about"],
        "i": ["am", "will", "think"],
        "i'll": ["be", "see", "let"],
        "i'm": ["not", "going", "so"],
        "if": ["you", "I", "we"],
        "in": ["the", "a", "my"],
        "into": ["the", "it", "a"],
        "is": ["a", "the", "not"],
        "it": ["is", "was", "will"],
        "it's": ["a", "not", "been"],
        "just": ["a", "wanted", "in"],
        "keep": ["me", "it", "up"],
        "know": ["if", "what", "that"],
        "last": ["night", "week", "time"],
        "let": ["me", "us", "you"],
        "let's": ["go", "do", "see"],
        "like": ["to", "a", "that"],
        "long": ["time", "day", "as"],
        "look": ["forward", "at", "into"],
        "looking": ["forward", "for", "at"],
        "love": ["you", "it", "the"],
        "make": ["sure", "it", "a"],
        "making": ["sure", "it", "a"],
        "many": ["thanks", "people", "of"],
        "may": ["be", "have", "not"],
        "me": ["know", "a", "to"],
        "might": ["be", "have", "want"],
        "more": ["than", "of", "time"],
        "most": ["of", "important", "likely"],
        "much": ["better", "more", "appreciated"],
        "my": ["own", "way", "best"],
        "need": ["to", "a", "you"],
        "never": ["mind", "been", "know"],
        "new": ["year", "one", "to"],
        "next": ["week", "time", "to"],
        "nice": ["to", "one", "day"],
        "no": ["problem", "worries", "one"],
        "not": ["sure", "a", "the"],
        "now": ["that", "I", "we"],
        "of": ["the", "course", "a"],
        "on": ["the", "my", "a"],
        "one": ["of", "day", "more"],
        "only": ["one", "a", "if"],
        "or": ["not", "the", "a"],
        "other": ["than", "people", "side"],
        "our": ["team", "own", "next"],
        "out": ["of", "there", "for"],
        "over": ["the", "there", "to"],
        "per": ["day", "person", "week"],
        "please": ["let", "send", "check"],
        "put": ["it", "the", "them"],
        "really": ["good", "appreciate", "like"],
        "right": ["now", "away", "there"],
        "run": ["out", "into", "the"],
        "say": ["that", "hi", "it"],
        "see": ["you", "it", "if"],
        "she": ["is", "was", "said"],
        "should": ["be", "we", "have"],
        "so": ["much", "far", "that"],
        "some": ["of", "time", "people"],
        "something": ["like", "else", "to"],
        "soon": ["as", "after"],
        "sorry": ["for", "about", "to"],
        "sounds": ["good", "great", "like"],
        "still": ["have", "not", "waiting"],
        "such": ["a", "as", "an"],
        "take": ["a", "care", "the"],
        "talk": ["to", "about", "soon"],
        "than": ["the", "a", "I"],
        "thank": ["you"],
        "thanks": ["for", "again", "so"],
        "that": ["is", "the", "would"],
        "that's": ["great", "a", "what"],
        "the": ["best", "same", "first"],
        "their": ["own", "way", "time"],
        "them": ["to", "and", "in"],
        "then": ["I", "we", "the"],
        "there": ["is", "are", "was"],
        "these": ["are", "days", "things"],
        "they": ["are", "will", "have"],
        "this": ["is", "week", "time"],
        "time": ["to", "for", "of"],
        "to": ["be", "the", "get"],
        "today": ["and", "at", "is"],
        "together": ["with", "and", "soon"],
        "tomorrow": ["morning", "at", "and"],
        "tonight": ["at", "and", "for"],
        "too": ["much", "many", "late"],
        "try": ["to", "it", "again"],
        "up": ["to", "with", "the"],
        "very": ["much", "good", "nice"],
        "wait": ["for", "until", "to"],
        "want": ["to", "you", "a"],
        "was": ["a", "the", "not"],
        "we": ["are", "can", "will"],
        "well": ["done", "as", "and"],
        "went": ["to", "well", "back"],
        "were": ["you", "not", "the"],
        "what": ["is", "do", "time"],
        "when": ["you", "I", "we"],
        "where": ["is", "are", "you"],
        "which": ["is", "one", "was"],
        "who": ["is", "are", "was"],
        "why": ["not", "is", "do"],
        "will": ["be", "you", "not"],
        "with": ["the", "you", "a"],
        "won't": ["be", "have", "work"],
        "work": ["on", "with", "out"],
        "would": ["be", "you", "like"],
        "you": ["are", "can", "have"],
        "your": ["own", "time", "help"],
    ]

    public static func predictions(
        after word: String?,
        personal: PersonalLanguageModel? = nil,
        limit: Int = 2
    ) -> [String] {
        guard limit > 0 else { return [] }
        var results: [String] = []
        func append(_ candidates: [String]) {
            for candidate in candidates
            where !results.contains(where: { $0.caseInsensitiveCompare(candidate) == .orderedSame }) {
                results.append(candidate)
            }
        }
        // The user's own habits outrank the generic bigram table.
        append(personal?.predictions(after: word, limit: limit) ?? [])
        if let word, let continuations = bigrams[word.lowercased()] {
            append(continuations)
        }
        append(fallback)
        return Array(results.prefix(limit))
    }
}
