import Foundation

/// Remembers a bounded editor suffix after text has already been learned.
/// The next unchanged word boundary can consume the marker instead of
/// learning or auto-correcting the final word a second time.
public struct ObservedTextSuffix: Sendable {
    private struct Marker: Sendable {
        let suffix: String
        let currentWord: String
    }

    private let maximumCharacters: Int
    private var marker: Marker?

    public init(maximumCharacters: Int = 64) {
        precondition(maximumCharacters > 0, "maximumCharacters must be positive")
        self.maximumCharacters = maximumCharacters
    }

    /// Records only insertions that end in the same in-progress word as the
    /// resulting editor context. Punctuated or space-terminated insertions do
    /// not need a boundary marker.
    public mutating func observe(
        committedText: String,
        contextBeforeInput context: String?
    ) {
        guard let context,
              case .typingWord(let committedWord) = TypingContextAnalyzer
                  .analyze(committedText).mode,
              case .typingWord(let currentWord) = TypingContextAnalyzer
                  .analyze(context).mode,
              committedWord == currentWord else {
            marker = nil
            return
        }

        marker = Marker(
            suffix: String(context.suffix(maximumCharacters)),
            currentWord: currentWord
        )
    }

    /// Always consumes the marker. Returns true only when both its exact
    /// bounded suffix and final word still match the editor.
    public mutating func consumeIfUnchanged(
        contextBeforeInput context: String?
    ) -> Bool {
        defer { marker = nil }
        guard let marker else { return false }
        return Self.matches(marker, context: context)
    }

    /// Keeps the marker across benign document callbacks generated by the
    /// insertion itself, but clears it after any external edit or cursor move.
    public mutating func retainIfUnchanged(
        contextBeforeInput context: String?
    ) {
        guard let marker else { return }
        if !Self.matches(marker, context: context) {
            self.marker = nil
        }
    }

    public mutating func clear() {
        marker = nil
    }

    private static func matches(_ marker: Marker, context: String?) -> Bool {
        guard let context,
              context.hasSuffix(marker.suffix),
              case .typingWord(let currentWord) = TypingContextAnalyzer
                  .analyze(context).mode else {
            return false
        }
        return currentWord == marker.currentWord
    }
}
